# Generated by Django 5.2.12 on 2026-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='books/', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fantasy', 'Фантастика'), ('Detective', 'Детектива'), ('Romantic', 'Романтика'), ('Prose', 'Проза'), ('Dramaturgy', 'Драматургия'), ('Mysticisme', 'Мистика')], max_length=10, null=True),
        ),
    ]
